#include "app_ble.h"
#include "app_uart.h"
#include <string.h>
//#include "WriteUserSFlash.h"

/* MTU size to be used by Client and Server after MTU exchange */
uint16 mtuSize      = CYBLE_GATT_MTU;   

/* Buffer for blerx data */
uint8 packetRX[BLE_PACKET_SIZE_MAX];
uint32 packetRXSize;
uint32 packetRXFlag;

/*******************************************************************************
* Function Name: HandleBleProcessing
********************************************************************************
*
* Summary:
*   Handles the BLE state machine for intiating different procedures
*   during different states of BLESS.
*
* Parameters:
*   None.
*
* Return:
*   None.
*
*******************************************************************************/
void HandleBleProcessing(void)
{    
    uint8 txDataClientConfigDesc[2];
    CYBLE_GATT_HANDLE_VALUE_PAIR_T  attrValue = { 
                                                    {(uint8 *)txDataClientConfigDesc, 2, 2}, 
                                                    CYBLE_CUSTOM_SERVICE_RX_FROM_APP_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE
                                                };
    switch (cyBle_state)
    {
        case CYBLE_STATE_ADVERTISING:
            break;
        
        case CYBLE_STATE_CONNECTED:
            CyBle_GattsReadAttributeValue(&attrValue, &cyBle_connHandle, CYBLE_GATT_DB_LOCALLY_INITIATED);
            break;
                
        case CYBLE_STATE_DISCONNECTED: 
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            break;       
            
        case CYBLE_STATE_INITIALIZING:
        case CYBLE_STATE_STOPPED:
        default:
            break;       
    }
}
uint8 ConnectFlag;

/*******************************************************************************
* Function Name: AppCallBack
********************************************************************************
*
* Summary:
*   Call back function for BLE stack to handle BLESS events
*
* Parameters:
*   event       - the event generated by stack
*   eventParam  - the parameters related to the corresponding event
*
* Return:
*   None.
*
*******************************************************************************/
void AppCallBack(uint32 event, void *eventParam)
{   
    CYBLE_GATT_ERR_CODE_T           errorCode;
    CYBLE_GATTS_WRITE_REQ_PARAM_T   *writeReqParam;
    CYBLE_API_RESULT_T apiResult;
    switch (event)//蓝牙的功能事件
    {
        case CYBLE_EVT_STACK_ON://开启状态
        /* This event is received when component is Started */
            /* Enter into discoverable mode so that remote can search it. */
            //apiResult = CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            if(apiResult != CYBLE_ERROR_OK)
            {   
                //ShowError();                
            }
            break;
            
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED://没有设备接入时
             CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);      //广播方式设为 快速
            break;
        case CYBLE_EVT_GATT_CONNECT_IND://连接完毕
                
            break;
        
        case CYBLE_EVT_GATTS_WRITE_CMD_REQ:            
            packetRXSize = ((CYBLE_GATTS_WRITE_REQ_PARAM_T *)eventParam)->handleValPair.value.len;
            memcpy(&packetRX[0], ((CYBLE_GATTS_WRITE_REQ_PARAM_T *)eventParam)->handleValPair.value.val, packetRXSize);
            packetRXFlag = 1u;
            break;
        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:            
            if(CYBLE_GATT_MTU > ((CYBLE_GATT_XCHG_MTU_PARAM_T *)eventParam)->mtu)
            {
                mtuSize = ((CYBLE_GATT_XCHG_MTU_PARAM_T *)eventParam)->mtu;
            }
            else
            {
                mtuSize = CYBLE_GATT_MTU;
            }
            break;
        case CYBLE_EVT_GATTS_WRITE_REQ:
            writeReqParam = (CYBLE_GATTS_WRITE_REQ_PARAM_T *) eventParam;
            
            if(CYBLE_CUSTOM_SERVICE_RX_FROM_APP_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE == \
                                                                    writeReqParam->handleValPair.attrHandle)
            {
             errorCode = CyBle_GattsWriteAttributeValue(&(writeReqParam->handleValPair), \
                                                0, &cyBle_connHandle, CYBLE_GATT_DB_PEER_INITIATED);
                
                if (CYBLE_GATT_ERR_NONE  == errorCode)
                {
                    CyBle_GattsWriteRsp(cyBle_connHandle); 
               //     UART_UartPutString("\n\rNotifications enabled\n\r");
               //     UART_UartPutString("\n\rStart entering data:\n\r");
                }
            }
           
            //
            packetRXSize = ((CYBLE_GATTS_WRITE_REQ_PARAM_T *)eventParam)->handleValPair.value.len;
            memcpy(&packetRX[0], ((CYBLE_GATTS_WRITE_REQ_PARAM_T *)eventParam)->handleValPair.value.val, packetRXSize);
            packetRXFlag = 1u;
            
            break;
     
        default:
            break;
    }
}

/* [] END OF FILE */
